### ISSUE TITLE
main missing ?

### ISSUE THREAD

**Issue by ericvincenterv** [OpenClassrooms-Student-Center/la_poo_avec_python#1]
Bonjour,

J'ai exécuté ce code en suivant ligne à ligne le tuto.
Je n'obtiens rien en résultat.
 Il ne manquerait pas un truc du style "main()" ?

**Comment by regisb** [comment]
Bonjour,

Comme vous pouvez le voir dans `model.py` la méthode `main()` existe bien et est bien appelée. Est-ce que vous êtes sûr qu'une fenêtre n'a pas été ouverte en arrière-plan ?

**Comment by ericvincenterv** [comment]
J'évoque le fichier model.py de ce lien : 
https://github.com/OpenClassrooms-Student-Center/la_poo_avec_python/tree/03_properties

Ce fichier là : 
https://github.com/OpenClassrooms-Student-Center/la_poo_avec_python/blob/03_properties/model.py

**Comment by celine-m-s** [comment]
Bonjour,
En effet, vous avez raison. Il manquait le main() dans ce chapitre. [Je viens de l'ajouter](https://github.com/OpenClassrooms-Student-Center/la_poo_avec_python/commit/5d839fe750dd9c770c7f801bff660d710e8b0576). 
Très bonne journée et merci du retour !
Céline
